Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -31,22 +31,22 @@ jobs:
             echo "OCI CLI already installed"
           fi
 
-      - name: Configure OKE Cluster
-        run: |
-          oci ce cluster create-kubeconfig --cluster-id ${{ vars.OKE_CLUSTER_OCID }} --file $HOME/.kube/config --region ${{ secrets.OCI_CLI_REGION }} --token-version 2.0.0          
-          sed -i "s|${{ env.oke_private_ip }}|127.0.0.1|g" $HOME/.kube/config
-          sleep 5
-          kubectl cluster-info
-          if [ $? == 0 ]
-          then
-            echo "---------------------------------------------------------------"
-            echo "Successfully Connected to your Private OKE Cluster"
-            echo "---------------------------------------------------------------"
-          else
-            echo "---------------------------------------------------------------"
-            echo "Unable to Authenticate with Private OKE Cluster"
-            echo "---------------------------------------------------------------"
-          fi
+      # - name: Configure OKE Cluster
+      #   run: |
+      #     oci ce cluster create-kubeconfig --cluster-id ${{ vars.OKE_CLUSTER_OCID }} --file $HOME/.kube/config --region ${{ secrets.OCI_CLI_REGION }} --token-version 2.0.0          
+      #     sed -i "s|${{ env.oke_private_ip }}|127.0.0.1|g" $HOME/.kube/config
+      #     sleep 5
+      #     kubectl cluster-info
+      #     if [ $? == 0 ]
+      #     then
+      #       echo "---------------------------------------------------------------"
+      #       echo "Successfully Connected to your Private OKE Cluster"
+      #       echo "---------------------------------------------------------------"
+      #     else
+      #       echo "---------------------------------------------------------------"
+      #       echo "Unable to Authenticate with Private OKE Cluster"
+      #       echo "---------------------------------------------------------------"
+      #     fi
 
       - name: Configure Kubectl for Oracle Container Engine for Kubernetes (OKE)
         # You may pin to the exact commit or the version.
